[package]
name = "dealer-test"
version = "1.0.0"
edition = "2021"
license = "Unlicense"

[dependencies]
dealer-core = { path = "../dealer-core" }
dealer-pbn = { path = "../dealer-pbn" }
gnurandom = { path = "../gnurandom" }
