[package]
name = "dealer-eval"
version = "0.1.0"
edition = "2021"
license = "Unlicense"

[dependencies]
dealer-core = { path = "../dealer-core" }
dealer-parser = { path = "../dealer-parser" }
dealer-dds = { path = "../dealer-dds" }
