[package]
name = "dealer-core"
version = "0.4.0"
edition = "2021"
license = "Unlicense"

[dependencies]
gnurandom = { path = "../gnurandom" }

[dev-dependencies]
dealer-pbn = { path = "../dealer-pbn" }
