[package]
name = "dealer-core"
version = "1.0.0"
edition = "2021"
license = "Unlicense"

[dependencies]
gnurandom = { path = "../gnurandom" }
bridge-types = { git = "https://github.com/Rick-Wilson/bridge-types" }

[dev-dependencies]
dealer-pbn = { path = "../dealer-pbn" }
